### ISSUE TITLE
illust.GetImage() returns null stream

### ISSUE THREAD

**Issue by DaOlHo** [jerwyk/PixeeSharp#1]
`var client = new PixeeSharpAppApi();
            await client.Login("user_wmxv8884", "Rkd4BeQD4Ynr76u");
            PixivIllustration illust = await client.GetIllustrationDetail("76194604");
            Stream imgStream = await illust.GetImage(PixeeSharp.Enums.ImageSize.Original);
            Image img = System.Drawing.Image.FromStream(imgStream);`
I'm trying to create a simple program that downloads an image from pixiv, but whenever I try to use anything, I get a null. I'm using .NET framework 4.7.2, with windows forms.

**Comment by jerwyk** [comment]
Sorry for not mentioning this but in fact you almost always need to use ImageSize.Large.
Original is an option in the returned the json but it is most likely going to be null. Not sure why pixiv is doing this but that should fix your issue.

**Comment by DaOlHo** [comment]
I tried using ImageSize.Large, but it still returns null

**Comment by jerwyk** [comment]
So I realized it is a issue about how I deserialize one of my objects and there was a issue with the client.
I have fixed it already on github and also published a new version on nuget. Hope that helps.

**Comment by DaOlHo** [comment]
I updated, but now when I try to compile it gives me an error that I should be using RestSharp 106.6.10.0, even though you upgraded the dependency on nuget

Here's the error:
`Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
'ImageArchiverApp.exe' (CLR v4.0.30319: ImageArchiverApp.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ImageArchiverApp.exe' (CLR v4.0.30319: ImageArchiverApp.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
System.IO.FileLoadException: Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at PixeeSharp.PixeeSharpBaseApi.<Login>d__30.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at PixeeSharp.PixeeSharpBaseApi.Login(String username, String password)
   at ImageArchiveApp.MainWindow.<PixivGalleryDownloadAsync>d__8.MoveNext() in C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\ImageArchiverApp.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ImageArchiveApp.MainWindow.<DownloadButton1_Click>d__2.MoveNext() in C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\ImageArchiverApp.cs:line 52

=== Pre-bind state information ===
LOG: DisplayName = RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75
 (Fully-specified)
LOG: Appbase = file:///C:/Users/dhodu/Dropbox/ImageArchiverApp/ImageArchiverApp/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : PixeeSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\bin\Debug\ImageArchiverApp.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75
LOG: Attempting download of new URL file:///C:/Users/dhodu/Dropbox/ImageArchiverApp/ImageArchiverApp/bin/Debug/RestSharp.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.`

**Comment by jerwyk** [comment]
Looks like a dependency issue when I packed my package. I really should test before I publish. Anyways I made an updated publish and it should really work this time.

**Comment by DaOlHo** [comment]
It works now, thank you for your time.
